### ISSUE TITLE
Addon not working?

### ISSUE THREAD

**Issue by kalwar** [kents1/vaadin-toast-addon#1]
> Could not parse POM http://maven.vaadin.com/vaadin-addons/org/vaadin/addons/vaadin-toastr/1.0.2/vaadin-toastr-1.0.2.pom
            > Could not resolve org.vaadin.addons:vaadin-toastr-addon:1.0.2.
               > Could not resolve org.vaadin.addons:vaadin-toastr-addon:1.0.2.
                  > Could not get resource 'http://mvn.jasoft.fi/maven2/org/vaadin/addons/vaadin-toastr-addon/1.0.2/vaadin-toastr-addon-1.0.2.pom'.
                     > Could not GET 'http://mvn.jasoft.fi/maven2/org/vaadin/addons/vaadin-toastr-addon/1.0.2/vaadin-toastr-addon-1.0.2.pom'.
                        > mvn.jasoft.fi: unknown error
      > Could not resolve org.vaadin.addons:vaadin-toastr:1.0.2.
         > Could not get resource 'http://mvn.jasoft.fi/maven2/org/vaadin/addons/vaadin-toastr/1.0.2/vaadin-toastr-1.0.2.pom'.
            > Could not HEAD 'http://mvn.jasoft.fi/maven2/org/vaadin/addons/vaadin-toastr/1.0.2/vaadin-toastr-1.0.2.pom'.
               > mvn.jasoft.fi

**Comment by kents1** [comment]
Issue is now resolved.  From version 1.0.7.
